project:
  type: website

website:
  title: "Jeff's 🗺 Adventures"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Exercise 1"
            href: "hands-on_ex/ex01/ho_ex01.html"
          - text: "Exercise 2"
            href: "hands-on_ex/ex02/ho_ex02.html"
          - text: "Exercise 3"
            href: "hands-on_ex/ex03/ho_ex03.html"
          - text: "Exercise 4"
            href: "hands-on_ex/ex04/ho_ex04.html"
          - text: "Exercise 5"
            href: "hands-on_ex/ex05/ho_ex05.html"
          - text: "Exercise 6"
            href: "hands-on_ex/ex06/ho_ex06.html"
          - text: "Exercise 8 & 9"
            href: "hands-on_ex/ex08/ho_ex08.html"
          - text: "Exercise 10 & 11"
            href: "hands-on_ex/ex10/ho_ex10.html"
          - text: "Exercise 12"
            href: "hands-on_ex/ex12/ho_ex12.html"
      - text: "In-class Exercise"
        menu: 
          - text: "Exercise 1"
            href: "in-class_ex/ex01/ic_ex01.html"
          - text: "Exercise 2"
            href: "in-class_ex/ex02/ic_ex02.html"
          - text: "Exercise 3"
            href: "in-class_ex/ex03/ic_ex03.html"
          - text: "Exercise 4"
            href: "in-class_ex/ex04/ic_ex04.html"
          - text: "Exercise 5"
            href: "in-class_ex/ex05/ic_ex05.html"
          - text: "Exercise 6"
            href: "in-class_ex/ex06/ic_ex06.html"
          - text: "Exercise 10"
            href: "in-class_ex/ex10/ic_ex10.html"
          - text: "Exercise 11"
            href: "in-class_ex/ex11/ic_ex11.html"
          - text: "Exercise 12"
            href: "in-class_ex/ex12/ic_ex12.html"
          - text: "Exercise 13"
            href: "in-class_ex/ex13/ic_ex13.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "Exercise 1"
            href: "take-home_ex/ex01/th_ex01.html"
          - text: "Exercise 2"
            href: "take-home_ex/ex02/th_ex02.html"
          - text: "Exercise 3"
            href: "take-home_ex/ex03/th_ex03.html"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

