project:
  type: website

website:
  title: "Jeff's 🗺 Adventures"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Exercise 1"
            href: "hands-on_ex/ex01/ho_ex01.html"
          - text: "Exercise 2"
            href: "hands-on_ex/ex02/ho_ex02.html"
          - text: "Exercise 3"
            href: "hands-on_ex/ex03/ho_ex03.html"
      - text: "In-class Exercise"
        menu: 
          - text: "Exercise 1"
            href: "in-class_ex/ex01/ic_ex01.html"
      - text: "Take-home Exercise"
        menu: 
          - text: "Exercise 1"
            href: "take-home_ex/ex01/to_ex01.html"
            
    right:
      - href: "listings.qmd"
        text: "Listings"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

