project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Exercise 1"
            href: "hands-on_ex/ex01/ex01.html"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

