---
title: "In-class Exercise 5"
author: "Jeffery Lau"
date: 09-16-2024
date-modified: "last-modified"
description: |
  In this exercise we learn how to work with GWmodel
categories:
  - In-class
format:
  html:
    toc: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel)
```

```{r}
#| eval: false
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
#| eval: false
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
#| eval: false
hunan <- left_join(hunan,hunan2012) %>%
  select(1:3,7,15,16,31,32)
```

```{r}
#| eval: false
write_rds(hunan, "data/rds/hunan.rds")
```

```{r}
#| echo: false
hunan <- read_rds("data/rds/hunan.rds")
```

```{r}
hunan_sp <- hunan %>%
  as_Spatial()
```

```{r}
# Geographically weighted summary statistics with adaptive bandwidth
bw_AIC <- bw.gwr(GDPPC ~ 1,
                 data = hunan_sp,
                 approach="AIC",
                 adaptive = TRUE,
                 kernel = "bisquare",
                 longlat = T)
```

```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                 data = hunan_sp,
                 approach="CV",
                 adaptive = TRUE,
                 kernel = "bisquare",
                 longlat = T)
```

```{r}
bw_CV_fixed <- bw.gwr(GDPPC ~ 1,
                 data = hunan_sp,
                 approach="CV",
                 adaptive = FALSE,
                 kernel = "bisquare",
                 longlat = T)
```

```{r}
bw_AIC_fixed <- bw.gwr(GDPPC ~ 1,
                 data = hunan_sp,
                 approach="AIC",
                 adaptive = FALSE,
                 kernel = "bisquare",
                 longlat = T)
```

Computing geographically weighted summary statistics

```{r}
gwstat <- gwss(data= hunan_sp,
               vars = "GDPPC",
               bw = bw_AIC,
               kernel = "bisquare",
               adaptive = TRUE,
               longlat = T)
```

Prepare the output data

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```

```{r}
hunan_gstat <- cbind(hunan, gwstat_df)
```

```{r}
tm_shape(hunan_gstat) +
  tm_fill("GDPPC_LM",
          n = 5,
          style = "quantile") +
  tm_borders(alpha = 0.5) +
  tm_layout(main.title = "Distributation of geographically weighted mean",
            main.title.position = "center",
            main.title.size = 2.0,
            legend.text.size = 1.2,
            legend.height = 1.5,
            legend.width = 1.5,
            frame= TRUE)
```
